version: '3.8'

services:
  haproxy:
    image: haproxy:2.8
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "3307:3307" # MySQL proxy port
      - "8404:8404" # Stats page
    depends_on:
      - mysql
      - mariadb
    networks:
      - craft-network
    healthcheck:
      test: ["CMD", "haproxy", "-c", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  craft-network:
    external: true