# craft configuration file

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  max_header_bytes: 1048576
  allowed_origins:
    - "*"

database:
  host: "localhost"
  port: 5432
  name: "craft"
  user: "postgres"
  password: ""
  ssl_mode: "disable"

logger:
  level: "info"
  format: "json"
  output: "stdout"
  fields:
    service: "craft"
