version: '3.8'

services:
  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio_data:/data
    networks:
      - craft-network

volumes:
  minio_data:

networks:
  craft-network:
    driver: bridge