version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"   # UDP port for tchannel
      - "6831:6831/udp"   # UDP port for receiving traces
      - "6832:6832/udp"   # UDP port for receiving traces
      - "5778:5778"       # HTTP port for service admin
      - "16686:16686"     # HTTP port for web UI
      - "14268:14268"     # HTTP port for receiving traces
      - "14250:14250"     # HTTP port for gRPC
      - "9411:9411"       # HTTP port for Zipkin
    networks:
      - craft-network

networks:
  craft-network:
    driver: bridge