version: '3.8'

services:
  valkey:
    image: valkeyio/valkey:latest
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    networks:
      - craft-network
    environment:
      VALKEY_CONFIG: /etc/valkey/valkey.conf
    command: ["valkey-server", "/etc/valkey/valkey.conf"]

  valkey-sentinel:
    image: valkeyio/valkey-sentinel:latest
    ports:
      - "26379:26379"
    networks:
      - craft-network
    environment:
      VALKEY_SENTINEL_CONFIG: /etc/valkey/sentinel.conf
    command: ["valkey-sentinel", "/etc/valkey/sentinel.conf"]

volumes:
  valkey_data:

networks:
  craft-network:
    driver: bridge