version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: craft
      POSTGRES_PASSWORD: craft
      POSTGRES_DB: craft
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - craft-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U craft"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  craft-network:
    driver: bridge