version: '3.8'

services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - craft-network

  sentinel:
    image: redis:alpine
    command: redis-sentinel /etc/sentinel.conf
    ports:
      - "26379:26379"
    networks:
      - craft-network
    volumes:
      - ./sentinel.conf:/etc/sentinel.conf

networks:
  craft-network:
    driver: bridge