version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - craft-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - craft-network
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:

networks:
  craft-network:
    driver: bridge